steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'asia-south1-docker.pkg.dev/republic-world-prod/rweb/svelte',
        '.'
      ]

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      [
        'push',
        'asia-south1-docker.pkg.dev/republic-world-prod/rweb/svelte'
      ]

  # Step 3: Deploy the first service (app.yaml)
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      [
        'app', 'deploy',
        '--image-url', 'asia-south1-docker.pkg.dev/republic-world-prod/rweb/svelte',
        '--quiet'  # Suppresses interactive prompts
      ]

# Specifies the images that are expected to be built and pushed
images:
  - 'asia-south1-docker.pkg.dev/republic-world-prod/rweb/svelte'
