
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui-deployment
  labels:
    app: webui
spec:
  replicas: 2  # Define the number of replicas (pods)
  selector:
    matchLabels:
      app: webui
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
        - name: webui
          image: asia-south1-docker.pkg.dev/genuine-ridge-446107-a4/test-repo/webui:latest  # Placeholder image name
          ports:
            - containerPort: 8086  # The port your app listens on inside the container
          env:
            - name: ENVIRONMENT
              value: "production"
          resources:
            limits:
              memory: "64Mi"
              cpu: "0.5"
            requests:
              memory: "32Mi"
              cpu: "0.5"
---
apiVersion: v1
kind: Service
metadata:
  name: webui-service
spec:
  selector:
    app: webui
  ports:
    - protocol: TCP
      port: 8086  # Port exposed outside the cluster
      targetPort: 8086  # Port on which your container is listening
  type: LoadBalancer  # Exposes the service to external traffic
