apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: republicschool-ui-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"              # Use GCP HTTP(S) Load Balancer  # Optional: for HTTPS cert if you have one
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: republicschool-ui-service
            port:
              number: 80
