apiVersion: v1
kind: Service
metadata:
  name: republicschool-ui-service
spec:
  type: LoadBalancer
  selector:
    app: republicschool-ui
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3002

