name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: genuine-ridge-446107-a4
  GKE_CLUSTER: myfirstcluster   # Updated cluster name here
  GKE_ZONE: asia-southeast1-b   # Updated zone here
  DEPLOYMENT_NAME: sample-deployment # Add your deployment name here.
  IMAGE: mywebsite

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}  # Store your Google Cloud Project ID as a secret
          credentials_json: ${{ secrets.GCP_SA_KEY }}  # Store your service account JSON key in GitHub Secrets
         # install_components: 'gke-gcloud-auth-plugin'  # Ensure the plugin is installed by default

      - name: Set up GKE credentials
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}  # Service account key stored in GitHub Secrets

      - name: Configure GKE context
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} \
            --zone ${{ env.GKE_ZONE }} \
            --project ${{ env.PROJECT_ID }}

      - name: Sync files to GKE pod
        run: |
          POD_NAME=$(kubectl get pods --selector=app=ubuntu,pod-template-hash=766b499fc7 -o jsonpath='{.items[0].metadata.name}')
          kubectl cp ./ $POD_NAME:/deploy
          
      - name: Authenticate Docker to GCR
        run: |
          gcloud auth configure-docker gcr.io
          # If using Artifact Registry, use this:
          # gcloud auth configure-docker ${env.GKE_ZONE}-docker.pkg.dev

      - name: Build Docker image 
        run: |
          docker build -t gcr.io/${{ env.PROJECT_ID }}/web-ui .

      - name: Push Docker image to Google Container Registry
        run: |
          docker push gcr.io/${{ env.PROJECT_ID }}/web-ui

      - name: Deploy to GKE
        run: |
          # Apply Kubernetes manifests to deploy the application
          kubectl apply -f kubernetes/deployment.yml  # Path to your deployment.yaml in your repo
          kubectl apply -f kubernetes/service.yml     # If you have a service definition

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/sampledeployment
