name: Build and Deploy to GKE

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: genuine-ridge-446107-a4
  GKE_CLUSTER: myfirstcluster   # Updated cluster name here
  GKE_ZONE: asia-southeast1-b   # Updated zone here
  DEPLOYMENT_NAME: sample-deployment # Add your deployment name here.
  IMAGE: mywebsite
  
jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GKE credentials
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}  # Service account key stored in GitHub Secrets

      - name: Configure GKE context
        run: |
          gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} \
            --zone ${{ env.GKE_ZONE }} \
            --project ${{ env.PROJECT_ID }}
            
      - name: Sync files to GKE pod
        run: |
         kubectl exec -it ubuntu-deployment-766b499fc7-s5c2g -- mkdir -p /deploy
         kubectl cp ./ ubuntu-deployment-766b499fc7-s5c2g:/deploy --recursive
        
      - name: Build Docker image 
        run: |
          docker build -t gcr.io/${{ env.GCP_PROJECT_ID }}/web-ui .

      - name: Push Docker image to Google Container Registry (if Docker is involved)
        run: |
          docker push gcr.io/${{ env.GCP_PROJECT_ID }}/web-ui

      - name: Deploy to GKE
        run: |
          # Apply Kubernetes manifests to deploy the application
          kubectl apply -f kubernetes/deployment.yml  # Path to your deployment.yaml in your repo
          kubectl apply -f kubernetes/service.yml     # If you have a service definition

      - name: Verify deployment
        run: |
          kubectl rollout status deployment/sampledeployment
