
name: Deploy Nginx

on:
  push:
    branches:
    - 'develop'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v2

   # - name: install the gcloud cli
   #   uses: google-github-actions/setup-gcloud@v0
   #   with:
     #   project_id: ${{ secrets.GCLOUD_PROJECT }}
     #   service_account_key: ${{ secrets.GKE_SA_KEY }}
      #  install_components: 'gke-gcloud-auth-plugin'
      #  export_default_credentials: true
    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
          project_id: ${{ secrets.GCLOUD_PROJECT_ID }}  # Store your Google Cloud Project ID as a secret
          credentials_json: ${{ secrets.GKE_SA_KEY }}  # Store your service account JSON key in GitHub Secrets
          install_components: 'gke-gcloud-auth-plugin'  # Ensure the plugin is installed by default
        
    - name: Set up GKE credentials
      uses: google-github-actions/auth@v0.4.0
      with:
       credentials_json: ${{ secrets.GKE_SA_KEY }}  # Service account key stored in GitHub Secrets
    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev
    - name: Build Docker image
      run: |
         docker build --build-arg VITE_FB_ID=1923161321262442  --build-arg VITE_GOOGLE_ID=1098766585632-2n7ik4lrosm8kdh1ub2v594clieulu6v.apps.googleusercontent.com --build-arg  VITE_JW_LIVE_TV_ENGLISH=0JMA8rXq --build-arg VITE_JW_LIVE_TV_HINDI=KYQv7H88  --build-arg VITE_JW_LIVE_TV_BANGLA=jhPBndGO --build-arg VITE_GA_ID=G-5R3HXP63GC --build-arg VITE_PIN_INTEREST=0557bda55a05238368f86a9e15dca956 --build-arg VITE_GOOGLE_SITE_VERFICATION=cU_o7P6kj1ep1tjsazcIG4QcPL5NCBOdZObrhg8xUAU --build-arg VITE_APPLE_ID=1326556994 --build-arg VITE_FB_APP_ID=1938877716402788 --build-arg VITE_FB_PAGE=1159346367512575 --build-arg VITE_YANDEX_ID=9453f2e375ab432b -t "asia-south1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/test-repo/webui1:latest" .
         docker push asia-south1-docker.pkg.dev/${{ secrets.GCLOUD_PROJECT_ID }}/test-repo/webui1:latest

    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GCLOUD_PROJECT }}
      run: |
        gcloud container clusters get-credentials cluster-3 --region us-central1 --project genuine-ridge-446107-a4
        #gcloud container clusters get-credentials myfirstcluster --zone asia-southeast1-b --project genuine-ridge-446107-a4
        # sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" resources.yaml
        kubectl apply -f deployment.yml
