name: Deploy to GKE

on:
  push:
    branches:
      - develo

env:
  PROJECT_ID: genuine-ridge-446107-a4
  GKE_CLUSTER: myfirstcluster
  GKE_ZONE: asia-southeast1-b
  Region: asia-south1
  IMAGE: web-ui
  DEPLOYMENT_NAME: webui-deployment
  CONTAINER_REGISTRY: asia-south1-docker.pkg.dev/genuine-ridge-446107-a4/registry

jobs:
  deploy:
    name: Deploy to GKE
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GKE_SA_KEY }}'

    - name: Install gke-gcloud-auth-plugin
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Get GKE credentials
      run: |
        gcloud container clusters get-credentials ${{ env.GKE_CLUSTER }} --zone ${{ env.GKE_ZONE }} --project ${{ env.PROJECT_ID }}

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker asia-south1-docker.pkg.dev

    - name: Build Docker image
      run: |
        docker build \
          --tag "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE }}:$GITHUB_SHA" \
          --tag "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE }}:latest" \
          .
        docker image prune -f

    - name: Push Docker image to Artifact Registry
      run: |
        docker push "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE }}:$GITHUB_SHA"
        docker push "${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE }}:latest"

    - name: Deploy to GKE
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl set image deployment/${{ env.DEPLOYMENT_NAME }} ${{ env.DEPLOYMENT_NAME }}="${{ env.CONTAINER_REGISTRY }}/${{ env.IMAGE }}:$GITHUB_SHA"
        kubectl rollout status deployment/${{ env.DEPLOYMENT_NAME }}
        kubectl get services -o wide
